print "True and True: " ,True and True , " T"
print "False and True: ", False and True, " F"
print "1 == 1 and 2 == 1 :", 1 == 1 and 2 == 1, " F"
print "\"test\" == \"test\":", "test" == "test", " T"
print "1 == 1 or 2 != 1 :", 1 == 1 or 2 != 1, " T"
print "True and 1 == 1 :", True and 1 == 1, " T"
print "False and 0 != 0 :", False and 0 != 0, " F"
print "True or 1 == 1 :", True or 1 == 1, " T"
print "\"test\" == \"testing\": ", "test" == "testing", " F"
print "1 != 0 and 2 == 1 :", 1 != 0 and 2 == 1, " F"
print "\"test\" != \"testing\" :", "test" != "testing", " T"
print "\"test\" == 1: ", "test" == 1, " F"
print "not (True and False): ", not (True and False), " T"
print "not (1 == 1 and 0 != 1) :", not (1 == 1 and 0 != 1), " F"
print "not (10 == 1 or 1000 == 1000): ", not (10 == 1 or 1000 == 1000), " F"
print "not (1 != 10 or 3 == 4) :", not (1 != 10 or 3 == 4), " F"
print "not (\"testing\" == \"testing\" and \"Zed\" == \"Cool Guy\"): ", not ("testing" == "testing" and "Zed" == "Cool Guy"), " T"
print "1 == 1 and (not (\"testing\" == 1 or 1 == 0)) : ", 1 == 1 and (not ("testing" == 1 or 1 == 0)), " T"
print "\"chunky\" == \"bacon\" and (not (3 == 4 or 3 == 3)) :", "chunky" == "bacon" and (not (3 == 4 or 3 == 3)), " F"
print "3 == 3 and (not (\"testing\" == \"testing\" or \"Python\" == \"Fun\")): ", 3 == 3 and (not ("testing" == "testing" or "Python" == "Fun")), " F"
print True and "Test"
